Repository wliamp/spring-boot-common-microservices, pull requests merged in 2025-08, with the labels that each got.

#39 dev/db-conn
  database-connector-api/build.gradle
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/component/SqlConnectionPool.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/constant/MongodbURI.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/constant/SqlConfigParam.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/constant/SqlDeniedCmd.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/constant/SqlJdbcURL.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/controller/DbController.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/dto/DbRequestDTO.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/dto/NosqlRequestDTO.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/dto/SqlRequestDTO.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/service/MongodbService.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/util/MongodbHandler.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/util/SqlHandler.java
Labels: enhancement

#42 module token-issuer-api
  token-issuer-api/build.gradle
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/TokenIssuerAPI.java
  token-issuer-api/src/main/resources/application.properties
Labels: enhancement

#45 module database-connector-api
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/constant/MongodbURI.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/constant/SqlJdbcURL.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/dto/DbRequestDTO.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/dto/NosqlRequestDTO.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/dto/SqlRequestDTO.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/service/MongodbService.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/util/SqlHandler.java
Labels: duplicate

#46 dev/db-conn
  database-connector-api/build.gradle
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/component/HeaderValueAllowed.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/component/HeaderValueFilter.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/component/SqlConnectionPool.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/config/SecurityConfig.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/controller/DbController.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/service/MongodbService.java
  database-connector-api/src/main/java/vn/chuot96/dbconnapi/service/SqlService.java
  database-connector-api/src/main/resources/application.properties
Labels: enhancement

#47 module verifi-3rd-provider-api
  verify-3rd-provider-api/build.gradle
  verify-3rd-provider-api/src/main/resources/application.properties
Labels: duplicate

#50 module token-issuer-api
  token-issuer-api/build.gradle
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/component/TokenCustomize.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/controller/TokenController.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/service/TokenService.java
  token-issuer-api/src/main/resources/application.properties
Labels: duplicate, enhancement

#51 dev/jwt-iss
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/component/HeaderValueAllowed.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/component/HeaderValueFilter.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/component/TokenCustomize.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/config/SecurityConfig.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/config/TokenConfig.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/constant/Token.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/controller/TokenController.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/dto/RequestDTO.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/service/TokenService.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/util/AccessTokenHandler.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/util/RefreshTokenHandler.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/util/TokenHandler.java
  token-issuer-api/src/test/java/vn/chuot96/jwtissapi/TokenDurationIssuerAPITests.java
Labels: duplicate

#53 dev/verify-3rd
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/component/ExternalFileReader.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/component/FacebookOauthProvider.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/component/FirebaseOtpProvider.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/component/GoogleOauthProvider.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/constant/Message.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/constant/Provider.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/controller/Controller.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/dto/RequestDTO.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/dto/TokenRequestDTO.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/service/ForwardService.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/service/OauthService.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/service/OtpService.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/util/OauthHandler.java
  verify-3rd-provider-api/src/main/java/vn/chuot96/verify3rdapi/util/OtpHandler.java
Labels: duplicate

#56 module token-issuer-api
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/TokenIssuerAPI.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/compo/ExternalFileReader.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/compo/HeaderValueAllowed.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/compo/HeaderValueFilter.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/compo/TokenCustomize.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/component/HeaderValueAllowed.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/config/SecurityConfig.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/controller/Controller.java
  token-issuer-api/src/main/java/vn/chuot96/jwtissapi/service/TokenService.java
  token-issuer-api/src/main/resources/application-issuer1.properties
  token-issuer-api/src/main/resources/application.properties
Labels: duplicate, enhancement

#65 module client-gateway
  client-gateway/src/main/java/vn/chuot96/clientgw/compo/AddRequestHeader.java
  client-gateway/src/main/java/vn/chuot96/clientgw/compo/ExternalFileReader.java
  client-gateway/src/main/resources/application-gate1.properties
Labels: duplicate

#66 dev/auth
  authentication-service/build.gradle
  authentication-service/src/main/java/vn/chuot96/authservice/anno/ForwardPriority.java
  authentication-service/src/main/java/vn/chuot96/authservice/compo/ForwardHelper.java
  authentication-service/src/main/java/vn/chuot96/authservice/compo/ForwardPriorityAspect.java
  authentication-service/src/main/java/vn/chuot96/authservice/compo/RedisHelper.java
  authentication-service/src/main/java/vn/chuot96/authservice/config/RedisConfig.java
  authentication-service/src/main/java/vn/chuot96/authservice/controller/Controller.java
  authentication-service/src/main/java/vn/chuot96/authservice/dto/UserInfo.java
  authentication-service/src/main/java/vn/chuot96/authservice/model/Acc.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/AccService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/AuthService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/ForwardService.java
  authentication-service/src/main/java/vn/chuot96/authservice/util/Generator.java
  authentication-service/src/main/resources/application-auth1.properties
Labels: enhancement

#68 module third-party-verify
  third-party-verify/build.gradle
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/FacebookOauthParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/FirebaseOtpParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/ForwardHelper.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/GoogleOauthParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/OauthParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/OtpParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/constant/Party.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/controller/Controller.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/dto/RequestDTO.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/dto/User.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/dto/UserDTO.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/exception/GlobalExceptionHandler.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/service/ForwardService.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/service/OauthService.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/service/OtpService.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/util/OauthHandler.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/util/OtpHandler.java
  third-party-verify/src/main/resources/application-verify1.properties
Labels: duplicate

#69 dev/verify-3rd
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/ExternalFileReader.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/FacebookOauthParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/FirebaseOtpParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/ForwardHelper.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/compo/GoogleOauthParty.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/service/ForwardService.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/service/OauthService.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/service/OtpService.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/util/OauthHandler.java
  third-party-verify/src/main/java/vn/chuot96/verify3rd/util/OtpHandler.java
Labels: duplicate

#75 dev/auth
  authentication-service/build.gradle
  authentication-service/src/main/java/vn/chuot96/authservice/compo/GuestHelper.java
  authentication-service/src/main/java/vn/chuot96/authservice/compo/TokenHelper.java
  authentication-service/src/main/java/vn/chuot96/authservice/controller/Controller.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/AuthService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/authenticate/LoginService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/authenticate/LogoutService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/authenticate/RelogService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/database/AccAudService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/database/AccScopeService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/database/AccService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/database/AudService.java
  authentication-service/src/main/java/vn/chuot96/authservice/service/database/ScopeService.java
Labels: duplicate, enhancement

#84 feat(pay): initial packages, classes and code base
  payment-service/build.gradle
  payment-service/src/main/java/io/wliamp/pay/compo/PaymentProcessor.java
  payment-service/src/main/java/io/wliamp/pay/constant/TransactionStatus.java
  payment-service/src/main/java/io/wliamp/pay/dto/Request.java
  payment-service/src/main/java/io/wliamp/pay/dto/Response.java
  payment-service/src/main/java/io/wliamp/pay/entity/Payment.java
  payment-service/src/main/java/io/wliamp/pay/repo/PaymentRepo.java
  payment-service/src/main/java/io/wliamp/pay/service/PaymentService.java
Labels: enhancement
